site_name: NMCP Data Mapping progress report
site_url: https://hamza-ye.github.io/snt-docs/
site_author: Hamza
repo_name: Hamza-ye/snt-docs
repo_url: https://github.com/Hamza-ye/snt-docs
edit_uri: edit/master/documentation/docs/